-- Medina Ziyarat batch: stops #3–#5 (Uhud, Aliya Date Garden, Al-Baqi).
-- Coordinates are stored explicitly so MapKit never resolves a free-text place name.

INSERT OR REPLACE INTO ziyarat_places (
  id, route_id, slug, title, title_ar, category, short_description, long_description,
  interesting_facts_json, visit_notes, visit_type, duration_minutes, latitude, longitude,
  address, map_label, route_order, status, created_by, created_at, updated_at
) VALUES (
  'mount-uhud', 'medina-main', 'mount-uhud', 'Mount Uhud', 'جبل أُحد', 'mountain', 'A major historic landmark north of Madinah, where the Battle of Uhud took place in 3 AH.', 'Mount Uhud is one of Madinah’s best-known natural and historical landmarks. It extends for about seven kilometers north of the Prophet’s Mosque and reaches about 1,077 meters above sea level. At its foothills the Battle of Uhud took place in 3 AH (625 CE), during which 70 companions were martyred. For the journey map, iumrah uses the visitor area at the Uhud battlefield near the southwestern foothills, close to Jabal al-Rumah and the Martyrs’ Cemetery, rather than an arbitrary point in the middle of the mountain.', '["Mount Uhud extends for about 7 km and is roughly 2–3 km wide.","The Battle of Uhud took place at its foothills in 3 AH (625 CE).","Jabal al-Rumah and the Uhud Martyrs’ Cemetery are part of the same historic landscape."]', 'Historical stop. Plan about 30–45 minutes. The route point is at the visitor area by the foothills; climbing the mountain is not part of this stop. Follow the guide and current local directions.', 'stop', 40, 24.50295, 39.61132, 'Uhud Battle Site, Sayyid al-Shuhada, Madinah, Saudi Arabia', 'Mount Uhud · Uhud visitor area', 3, 'published', 'seed', '2026-09-09T13:30:00.000Z', '2026-09-09T13:30:00.000Z'
);

INSERT OR REPLACE INTO ziyarat_images (
  id, place_id, object_key, content_type, byte_size, width, height, position, created_at
) VALUES
  ('uhud-1', 'mount-uhud', 'ziyarats/mount-uhud/uhud-1.jpg', 'image/jpeg', 593258, 1254, 1254, 0, '2026-09-09T13:30:00.000Z'),
  ('uhud-2', 'mount-uhud', 'ziyarats/mount-uhud/uhud-2.jpg', 'image/jpeg', 693278, 1254, 1254, 1, '2026-09-09T13:30:00.000Z'),
  ('uhud-3', 'mount-uhud', 'ziyarats/mount-uhud/uhud-3.jpg', 'image/jpeg', 605233, 1254, 1254, 2, '2026-09-09T13:30:00.000Z'),
  ('uhud-4', 'mount-uhud', 'ziyarats/mount-uhud/uhud-4.jpg', 'image/jpeg', 699578, 1254, 1254, 3, '2026-09-09T13:30:00.000Z'),
  ('uhud-5', 'mount-uhud', 'ziyarats/mount-uhud/uhud-5.jpg', 'image/jpeg', 570002, 1254, 1254, 4, '2026-09-09T13:30:00.000Z');

INSERT OR REPLACE INTO ziyarat_place_translations (
  place_id, locale, title, short_description, long_description,
  interesting_facts_json, visit_notes, created_at, updated_at
) VALUES
(
  'mount-uhud', 'ru', 'Гора Ухуд', 'Один из главных исторических символов Медины — у подножия Ухуда в 3 году хиджры произошла битва при Ухуде.', 'Гора Ухуд — одна из самых известных природных и исторических достопримечательностей Медины. Она тянется примерно на семь километров к северу от Мечети Пророка и достигает около 1 077 м над уровнем моря. У её подножия в 3 году хиджры (625 г.) произошла битва при Ухуде, в которой погибли 70 сподвижников. Для карты iumrah используется реальная зона посещения у исторического поля битвы на юго-западном подножии, рядом с Джабаль ар-Рума и кладбищем шахидов, а не случайная точка в центре горного массива.', '["Ухуд тянется примерно на 7 км, его ширина составляет около 2–3 км.","Битва при Ухуде произошла у подножия горы в 3 году хиджры (625 г.).","Рядом находятся Джабаль ар-Рума и кладбище шахидов Ухуда — части одного исторического ландшафта."]', 'Историческая остановка примерно на 30–45 минут. Точка маршрута находится в зоне посещения у подножия; подъём на гору в эту остановку не входит. Следуйте указаниям гида и действующим местным правилам.', '2026-09-09T13:30:00.000Z', '2026-09-09T13:30:00.000Z'
),
(
  'mount-uhud', 'uz', 'Uhud tog‘i', 'Madinaning eng muhim tarixiy ramzlaridan biri — Uhud jangi hijriy 3-yilda shu tog‘ etagida bo‘lib o‘tgan.', 'Uhud tog‘i Madinaning eng mashhur tabiiy va tarixiy maskanlaridan biridir. U Payg‘ambar masjididan shimolda taxminan yetti kilometrga cho‘ziladi va dengiz sathidan qariyb 1 077 metr balandlikka yetadi. Hijriy 3-yilda (milodiy 625-yil) uning etagida Uhud jangi bo‘lib o‘tgan va unda 70 nafar sahoba shahid bo‘lgan. iumrah xaritasida tog‘ning o‘rtasidagi tasodifiy nuqta emas, balki janubi-g‘arbiy etakdagi Uhud jang maydoni, Jabal ar-Rumah va shahidlar qabristoniga yaqin haqiqiy tashrif hududi ishlatiladi.', '["Uhud tog‘i taxminan 7 km uzunlikda va 2–3 km kenglikda.","Uhud jangi hijriy 3-yilda (625-yil) tog‘ etagida bo‘lib o‘tgan.","Jabal ar-Rumah va Uhud shahidlari qabristoni shu tarixiy hududning bir qismidir."]', 'Tarixiy to‘xtash joyi, odatda 30–45 daqiqa. Yo‘nalish nuqtasi tog‘ etagidagi tashrif hududida; tog‘ga chiqish bu to‘xtash dasturiga kirmaydi. Gid va amaldagi mahalliy ko‘rsatmalarga rioya qiling.', '2026-09-09T13:30:00.000Z', '2026-09-09T13:30:00.000Z'
),
(
  'mount-uhud', 'uz-cyrl', 'Уҳуд тоғи', 'Мадинанинг энг муҳим тарихий рамзларидан бири — Уҳуд жанги ҳижрий 3-йилда шу тоғ этагида бўлиб ўтган.', 'Уҳуд тоғи Мадинанинг энг машҳур табиий ва тарихий масканларидан биридир. У Пайғамбар масжидидан шимолда тахминан етти километрга чўзилади ва денгиз сатҳидан қарийб 1 077 метр баландликка етади. Ҳижрий 3-йилда (милодий 625-йил) унинг этагида Уҳуд жанги бўлиб ўтган ва унда 70 нафар саҳоба шаҳид бўлган. iumrah харитасида тоғнинг ўртасидаги тасодифий нуқта эмас, балки жануби-ғарбий этакдаги Уҳуд жанг майдони, Жабал ар-Румаҳ ва шаҳидлар қабристонига яқин ҳақиқий ташриф ҳудуди ишлатилади.', '["Уҳуд тоғи тахминан 7 км узунликда ва 2–3 км кенгликда.","Уҳуд жанги ҳижрий 3-йилда (625-йил) тоғ этагида бўлиб ўтган.","Жабал ар-Румаҳ ва Уҳуд шаҳидлари қабристони шу тарихий ҳудуднинг бир қисмидир."]', 'Тарихий тўхташ жойи, одатда 30–45 дақиқа. Йўналиш нуқтаси тоғ этагидаги ташриф ҳудудида; тоғга чиқиш бу тўхташ дастурига кирмайди. Гид ва амалдаги маҳаллий кўрсатмаларга риоя қилинг.', '2026-09-09T13:30:00.000Z', '2026-09-09T13:30:00.000Z'
),
(
  'mount-uhud', 'en', 'Mount Uhud', 'A major historic landmark north of Madinah, where the Battle of Uhud took place in 3 AH.', 'Mount Uhud is one of Madinah’s best-known natural and historical landmarks. It extends for about seven kilometers north of the Prophet’s Mosque and reaches about 1,077 meters above sea level. At its foothills the Battle of Uhud took place in 3 AH (625 CE), during which 70 companions were martyred. For the journey map, iumrah uses the visitor area at the Uhud battlefield near the southwestern foothills, close to Jabal al-Rumah and the Martyrs’ Cemetery, rather than an arbitrary point in the middle of the mountain.', '["Mount Uhud extends for about 7 km and is roughly 2–3 km wide.","The Battle of Uhud took place at its foothills in 3 AH (625 CE).","Jabal al-Rumah and the Uhud Martyrs’ Cemetery are part of the same historic landscape."]', 'Historical stop. Plan about 30–45 minutes. The route point is at the visitor area by the foothills; climbing the mountain is not part of this stop. Follow the guide and current local directions.', '2026-09-09T13:30:00.000Z', '2026-09-09T13:30:00.000Z'
);

INSERT OR REPLACE INTO ziyarat_places (
  id, route_id, slug, title, title_ar, category, short_description, long_description,
  interesting_facts_json, visit_notes, visit_type, duration_minutes, latitude, longitude,
  address, map_label, route_order, status, created_by, created_at, updated_at
) VALUES (
  'aliya-date-garden', 'medina-main', 'aliya-date-garden', 'Aliya Date Garden', 'مزارع عالية المدينة', 'garden', 'A palm garden in Qurban that shows the agricultural side of Madinah and its long tradition of date cultivation.', 'Aliya Date Garden is a concrete visitor point within the palm-growing landscape of southern Madinah. The wider Aliat Al-Madinah farming zone is known for dense date palms, traditional irrigation channels and date production, and Madinah’s official tourism site describes these farms as an important historical agricultural area. iumrah stores the exact Aliya Date Garden coordinate in Qurban so the route opens the intended garden instead of resolving to a random farm.', '["The Al-Aliyah area is one of Madinah’s best-known historic agricultural zones.","Dense palm groves and irrigation channels are characteristic of the farming landscape.","Madinah is famous for many local date varieties, including Ajwa."]', 'Short garden stop, usually about 20–30 minutes. Access and opening conditions can vary, so follow the guide’s current meeting point and instructions before entering or purchasing dates.', 'stop', 25, 24.449811, 39.627519, 'Qurban, Madinah 42316, Saudi Arabia', 'Aliya Date Garden · exact point', 4, 'published', 'seed', '2026-09-09T13:30:00.000Z', '2026-09-09T13:30:00.000Z'
);

INSERT OR REPLACE INTO ziyarat_images (
  id, place_id, object_key, content_type, byte_size, width, height, position, created_at
) VALUES
  ('date-garden-1', 'aliya-date-garden', 'ziyarats/aliya-date-garden/date-garden-1.jpg', 'image/jpeg', 734224, 1254, 1254, 0, '2026-09-09T13:30:00.000Z'),
  ('date-garden-2', 'aliya-date-garden', 'ziyarats/aliya-date-garden/date-garden-2.jpg', 'image/jpeg', 700365, 1254, 1254, 1, '2026-09-09T13:30:00.000Z'),
  ('date-garden-3', 'aliya-date-garden', 'ziyarats/aliya-date-garden/date-garden-3.jpg', 'image/jpeg', 789083, 1254, 1254, 2, '2026-09-09T13:30:00.000Z'),
  ('date-garden-4', 'aliya-date-garden', 'ziyarats/aliya-date-garden/date-garden-4.jpg', 'image/jpeg', 535140, 1254, 1254, 3, '2026-09-09T13:30:00.000Z'),
  ('date-garden-5', 'aliya-date-garden', 'ziyarats/aliya-date-garden/date-garden-5.jpg', 'image/jpeg', 768544, 1254, 1254, 4, '2026-09-09T13:30:00.000Z');

INSERT OR REPLACE INTO ziyarat_place_translations (
  place_id, locale, title, short_description, long_description,
  interesting_facts_json, visit_notes, created_at, updated_at
) VALUES
(
  'aliya-date-garden', 'ru', 'Финиковый сад Алия', 'Пальмовый сад в районе Курбан, показывающий сельскохозяйственную сторону Медины и её многовековую традицию выращивания фиников.', 'Aliya Date Garden — конкретная точка посещения среди пальмовых хозяйств южной Медины. Более широкий район ферм Аль-Алия известен густыми финиковыми пальмами, оросительными каналами и производством фиников; официальный туристический портал Медины относит эти фермы к важным историческим сельскохозяйственным зонам города. iumrah сохраняет точные координаты сада в районе Курбан, поэтому маршрут открывает нужное место, а не случайную ферму поблизости.', '["Район Аль-Алия — одна из известных исторических сельскохозяйственных зон Медины.","Для местного ландшафта характерны густые пальмовые рощи и оросительные каналы.","Медина известна многими сортами фиников, в том числе аджва."]', 'Короткая остановка примерно на 20–30 минут. Доступ и режим работы могут меняться, поэтому ориентируйтесь на актуальную точку встречи и указания гида перед входом или покупкой фиников.', '2026-09-09T13:30:00.000Z', '2026-09-09T13:30:00.000Z'
),
(
  'aliya-date-garden', 'uz', 'Aliya xurmo bog‘i', 'Qurban hududidagi xurmo bog‘i — Madinaning dehqonchilik muhiti va qadimiy xurmo yetishtirish an’anasini ko‘rsatadi.', 'Aliya Date Garden Madinaning janubidagi xurmo xo‘jaliklari orasidagi aniq tashrif nuqtasidir. Kengroq Al-Aliya dehqonchilik hududi zich xurmozorlar, sug‘orish ariqlari va xurmo yetishtirish bilan mashhur; Madinaning rasmiy turizm sayti bu fermalarni shaharning muhim tarixiy qishloq xo‘jaligi hududlaridan biri sifatida tasvirlaydi. iumrah Qurban hududidagi Aliya Date Garden koordinatasini aniq saqlaydi, shuning uchun xarita tasodifiy boshqa fermani emas, kerakli bog‘ni ochadi.', '["Al-Aliya Madinaning mashhur tarixiy dehqonchilik hududlaridan biridir.","Zich xurmozorlar va sug‘orish kanallari bu hudud manzarasining muhim qismidir.","Madina ko‘plab mahalliy xurmo navlari, jumladan Ajva bilan mashhur."]', 'Qisqa bog‘ to‘xtashi, odatda 20–30 daqiqa. Kirish va ish vaqti o‘zgarishi mumkin, shuning uchun bog‘ga kirish yoki xurmo xarid qilishdan oldin gidning joriy uchrashuv nuqtasi va ko‘rsatmalariga amal qiling.', '2026-09-09T13:30:00.000Z', '2026-09-09T13:30:00.000Z'
),
(
  'aliya-date-garden', 'uz-cyrl', 'Алия хурмо боғи', 'Қурбан ҳудудидаги хурмо боғи — Мадинанинг деҳқончилик муҳити ва қадимий хурмо етиштириш анъанасини кўрсатади.', 'Aliya Date Garden Мадинанинг жанубидаги хурмо хўжаликлари орасидаги аниқ ташриф нуқтасидир. Кенгроқ Ал-Алия деҳқончилик ҳудуди зич хурмозорлар, суғориш ариқлари ва хурмо етиштириш билан машҳур; Мадинанинг расмий туризм сайти бу фермаларни шаҳарнинг муҳим тарихий қишлоқ хўжалиги ҳудудларидан бири сифатида тасвирлайди. iumrah Қурбан ҳудудидаги Aliya Date Garden координатасини аниқ сақлайди, шунинг учун харита тасодифий бошқа фермани эмас, керакли боғни очади.', '["Ал-Алия Мадинанинг машҳур тарихий деҳқончилик ҳудудларидан биридир.","Зич хурмозорлар ва суғориш каналлари бу ҳудуд манзарасининг муҳим қисмидир.","Мадина кўплаб маҳаллий хурмо навлари, жумладан Ажва билан машҳур."]', 'Қисқа боғ тўхташи, одатда 20–30 дақиқа. Кириш ва иш вақти ўзгариши мумкин, шунинг учун боғга кириш ёки хурмо харид қилишдан олдин гиднинг жорий учрашув нуқтаси ва кўрсатмаларига амал қилинг.', '2026-09-09T13:30:00.000Z', '2026-09-09T13:30:00.000Z'
),
(
  'aliya-date-garden', 'en', 'Aliya Date Garden', 'A palm garden in Qurban that shows the agricultural side of Madinah and its long tradition of date cultivation.', 'Aliya Date Garden is a concrete visitor point within the palm-growing landscape of southern Madinah. The wider Aliat Al-Madinah farming zone is known for dense date palms, traditional irrigation channels and date production, and Madinah’s official tourism site describes these farms as an important historical agricultural area. iumrah stores the exact Aliya Date Garden coordinate in Qurban so the route opens the intended garden instead of resolving to a random farm.', '["The Al-Aliyah area is one of Madinah’s best-known historic agricultural zones.","Dense palm groves and irrigation channels are characteristic of the farming landscape.","Madinah is famous for many local date varieties, including Ajwa."]', 'Short garden stop, usually about 20–30 minutes. Access and opening conditions can vary, so follow the guide’s current meeting point and instructions before entering or purchasing dates.', '2026-09-09T13:30:00.000Z', '2026-09-09T13:30:00.000Z'
);

INSERT OR REPLACE INTO ziyarat_places (
  id, route_id, slug, title, title_ar, category, short_description, long_description,
  interesting_facts_json, visit_notes, visit_type, duration_minutes, latitude, longitude,
  address, map_label, route_order, status, created_by, created_at, updated_at
) VALUES (
  'al-baqi', 'medina-main', 'al-baqi', 'Al-Baqi Cemetery', 'مقبرة البقيع', 'cemetery', 'The historic cemetery immediately southeast of the Prophet’s Mosque, where many relatives, companions and early Muslims are buried.', 'Al-Baqi, also known as Baqi al-Gharqad, is the historic cemetery beside the Prophet’s Mosque and has been used since the earliest Muslim community in Madinah. Many members of the Prophet’s ﷺ family, companions and other prominent early Muslims are buried here. Today the cemetery is characterized by simple grave markers. Access arrangements can change, so iumrah uses the exact cemetery coordinate for map context while the live guide directs the group to the currently permitted visitor area.', '["Al-Baqi lies immediately southeast of the Prophet’s Mosque.","The cemetery dates to the earliest Islamic period in Madinah, around 622 CE.","Many members of the Prophet’s ﷺ family, companions and notable early Muslims are buried here."]', 'A quiet and respectful stop, usually about 20–30 minutes. Access rules and visiting times can change; follow current local instructions and the guide’s directions. Entry is not guaranteed as part of the route.', 'stop', 25, 24.46667, 39.61633, 'Al-Baqi Cemetery, Madinah, Saudi Arabia', 'Al-Baqi Cemetery · exact point', 5, 'published', 'seed', '2026-09-09T13:30:00.000Z', '2026-09-09T13:30:00.000Z'
);

INSERT OR REPLACE INTO ziyarat_images (
  id, place_id, object_key, content_type, byte_size, width, height, position, created_at
) VALUES
  ('baqi-1', 'al-baqi', 'ziyarats/al-baqi/baqi-1.jpg', 'image/jpeg', 543489, 1254, 1254, 0, '2026-09-09T13:30:00.000Z'),
  ('baqi-2', 'al-baqi', 'ziyarats/al-baqi/baqi-2.jpg', 'image/jpeg', 358327, 1254, 1254, 1, '2026-09-09T13:30:00.000Z'),
  ('baqi-3', 'al-baqi', 'ziyarats/al-baqi/baqi-3.jpg', 'image/jpeg', 462098, 1254, 1254, 2, '2026-09-09T13:30:00.000Z'),
  ('baqi-4', 'al-baqi', 'ziyarats/al-baqi/baqi-4.jpg', 'image/jpeg', 404277, 1254, 1254, 3, '2026-09-09T13:30:00.000Z'),
  ('baqi-5', 'al-baqi', 'ziyarats/al-baqi/baqi-5.jpg', 'image/jpeg', 413665, 1254, 1254, 4, '2026-09-09T13:30:00.000Z');

INSERT OR REPLACE INTO ziyarat_place_translations (
  place_id, locale, title, short_description, long_description,
  interesting_facts_json, visit_notes, created_at, updated_at
) VALUES
(
  'al-baqi', 'ru', 'Кладбище Аль-Баки', 'Историческое кладбище сразу к юго-востоку от Мечети Пророка, где похоронены многие родственники Пророка ﷺ, сподвижники и первые мусульмане.', 'Аль-Баки, также известное как Баки аль-Гаркад, — историческое кладбище рядом с Мечетью Пророка, используемое со времени ранней мусульманской общины Медины. Здесь похоронены многие члены семьи Пророка ﷺ, сподвижники и другие известные мусульмане первых поколений. Сегодня кладбище отличается простыми обозначениями могил. Порядок доступа может меняться, поэтому iumrah сохраняет точную координату самого кладбища для карты, а живой гид направляет группу к разрешённой на данный момент зоне посещения.', '["Аль-Баки находится непосредственно к юго-востоку от Мечети Пророка.","Кладбище относится к самому раннему исламскому периоду Медины — примерно с 622 года.","Здесь похоронены многие родственники Пророка ﷺ, сподвижники и известные мусульмане первых поколений."]', 'Спокойная и уважительная остановка примерно на 20–30 минут. Правила доступа и часы посещения могут меняться; следуйте действующим местным указаниям и инструкциям гида. Вход внутрь не гарантируется программой маршрута.', '2026-09-09T13:30:00.000Z', '2026-09-09T13:30:00.000Z'
),
(
  'al-baqi', 'uz', 'Al-Baqi qabristoni', 'Payg‘ambar masjidining janubi-sharqida joylashgan tarixiy qabriston; bu yerda Payg‘ambarimiz ﷺning ko‘plab qarindoshlari, sahobalar va ilk musulmonlar dafn etilgan.', 'Al-Baqi, Baqi al-Gharqad nomi bilan ham tanilgan, Payg‘ambar masjidi yonidagi tarixiy qabriston bo‘lib, Madinadagi ilk musulmon jamoasi davridan beri foydalanib kelinadi. Bu yerda Payg‘ambarimiz ﷺning ko‘plab oila a’zolari, sahobalar va ilk avlodlarning mashhur musulmonlari dafn etilgan. Bugungi qabristonda qabrlar oddiy belgilar bilan ko‘rsatiladi. Kirish tartibi o‘zgarishi mumkin, shu sabab iumrah xaritada qabristonning aniq koordinatasini saqlaydi, jonli gid esa guruhni ayni paytda ruxsat etilgan tashrif hududiga yo‘naltiradi.', '["Al-Baqi Payg‘ambar masjidining darhol janubi-sharqida joylashgan.","Qabriston Madinadagi eng ilk Islom davriga, taxminan 622-yilga borib taqaladi.","Bu yerda Payg‘ambarimiz ﷺning ko‘plab qarindoshlari, sahobalar va mashhur ilk musulmonlar dafn etilgan."]', 'Tinch va hurmat bilan o‘tiladigan to‘xtash, odatda 20–30 daqiqa. Kirish qoidalari va tashrif vaqtlari o‘zgarishi mumkin; joriy mahalliy ko‘rsatmalar va gid yo‘riqlariga rioya qiling. Yo‘nalish doirasida ichkariga kirish kafolatlanmaydi.', '2026-09-09T13:30:00.000Z', '2026-09-09T13:30:00.000Z'
),
(
  'al-baqi', 'uz-cyrl', 'Ал-Бақи қабристони', 'Пайғамбар масжидининг жануби-шарқида жойлашган тарихий қабристон; бу ерда Пайғамбаримиз ﷺнинг кўплаб қариндошлари, саҳобалар ва илк мусулмонлар дафн этилган.', 'Ал-Бақи, Бақи ал-Ғарқад номи билан ҳам танилган, Пайғамбар масжиди ёнидаги тарихий қабристон бўлиб, Мадинадаги илк мусулмон жамоаси давридан бери фойдаланиб келинади. Бу ерда Пайғамбаримиз ﷺнинг кўплаб оила аъзолари, саҳобалар ва илк авлодларнинг машҳур мусулмонлари дафн этилган. Бугунги қабристонда қабрлар оддий белгилар билан кўрсатилади. Кириш тартиби ўзгариши мумкин, шу сабаб iumrah харитада қабристоннинг аниқ координатасини сақлайди, жонли гид эса гуруҳни айни пайтда рухсат этилган ташриф ҳудудига йўналтиради.', '["Ал-Бақи Пайғамбар масжидининг дарҳол жануби-шарқида жойлашган.","Қабристон Мадинадаги энг илк Ислом даврига, тахминан 622-йилга бориб тақалади.","Бу ерда Пайғамбаримиз ﷺнинг кўплаб қариндошлари, саҳобалар ва машҳур илк мусулмонлар дафн этилган."]', 'Тинч ва ҳурмат билан ўтиладиган тўхташ, одатда 20–30 дақиқа. Кириш қоидалари ва ташриф вақтлари ўзгариши мумкин; жорий маҳаллий кўрсатмалар ва гид йўриқларига риоя қилинг. Йўналиш доирасида ичкарига кириш кафолатланмайди.', '2026-09-09T13:30:00.000Z', '2026-09-09T13:30:00.000Z'
),
(
  'al-baqi', 'en', 'Al-Baqi Cemetery', 'The historic cemetery immediately southeast of the Prophet’s Mosque, where many relatives, companions and early Muslims are buried.', 'Al-Baqi, also known as Baqi al-Gharqad, is the historic cemetery beside the Prophet’s Mosque and has been used since the earliest Muslim community in Madinah. Many members of the Prophet’s ﷺ family, companions and other prominent early Muslims are buried here. Today the cemetery is characterized by simple grave markers. Access arrangements can change, so iumrah uses the exact cemetery coordinate for map context while the live guide directs the group to the currently permitted visitor area.', '["Al-Baqi lies immediately southeast of the Prophet’s Mosque.","The cemetery dates to the earliest Islamic period in Madinah, around 622 CE.","Many members of the Prophet’s ﷺ family, companions and notable early Muslims are buried here."]', 'A quiet and respectful stop, usually about 20–30 minutes. Access rules and visiting times can change; follow current local instructions and the guide’s directions. Entry is not guaranteed as part of the route.', '2026-09-09T13:30:00.000Z', '2026-09-09T13:30:00.000Z'
);
