-- Makkah Ziyarats batch: six published stops and unrestricted media rows.
-- Coordinates are stored explicitly; the client does not geocode names at runtime.
INSERT OR REPLACE INTO ziyarat_routes (id,slug,city,country,title,subtitle,transport_mode,status,created_at,updated_at) VALUES ('makkah-main','makkah-ziyarat','Makkah','Saudi Arabia','Makkah Ziyarat','Sacred and historic places around Makkah','car','published','2026-09-11T16:30:00.000Z','2026-09-11T16:30:00.000Z');

INSERT OR REPLACE INTO ziyarat_places (
  id,route_id,slug,title,title_ar,category,short_description,long_description,interesting_facts_json,visit_notes,visit_type,duration_minutes,latitude,longitude,address,map_label,route_order,status,created_by,created_at,updated_at
) VALUES (
  'jabal-thawr', 'makkah-main', 'jabal-thawr', 'Jabal Thawr / Cave of Thawr', 'جبل ثور / غار ثور', 'mountain', 'A historic mountain south of Makkah, home to the cave associated with the Prophet’s ﷺ Hijrah to Madinah.', 'Jabal Thawr is a mountain south of Makkah. Near its summit is the Cave of Thawr, where the Prophet Muhammad ﷺ and Abu Bakr رضي الله عنه took refuge for three nights during the Hijrah before continuing toward Madinah. The Qur’an refers to the event of the two companions in the cave in Surah At-Tawbah 9:40. The saved map point marks the cave itself; reaching it requires a demanding mountain climb and should not be treated as an ordinary short walk.', '["The Cave of Thawr is connected with the Hijrah from Makkah to Madinah.","The Prophet ﷺ and Abu Bakr رضي الله عنه remained in the cave for three nights.","The Qur’an mentions the event of the two companions in the cave in Surah At-Tawbah 9:40."]', 'Historic stop. The map pin marks the cave, but the ascent is steep and physically demanding. Follow the live guide and current local access guidance; viewing the mountain does not require climbing to the cave.', 'stop', 30, 21.3768194, 39.8500389, 'Jabal Thawr, Makkah, Saudi Arabia', 'Cave of Thawr · exact point', 1, 'published', 'seed', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z'
);

INSERT OR REPLACE INTO ziyarat_images (id,place_id,object_key,content_type,byte_size,width,height,position,created_at) VALUES
  ('thawr-1', 'jabal-thawr', 'ziyarats/jabal-thawr/thawr-1.jpg', 'image/jpeg', 604345, 1254, 1254, 0, '2026-09-11T16:30:00.000Z'),
  ('thawr-2', 'jabal-thawr', 'ziyarats/jabal-thawr/thawr-2.jpg', 'image/jpeg', 803472, 1254, 1254, 1, '2026-09-11T16:30:00.000Z'),
  ('thawr-3', 'jabal-thawr', 'ziyarats/jabal-thawr/thawr-3.jpg', 'image/jpeg', 840846, 1254, 1254, 2, '2026-09-11T16:30:00.000Z'),
  ('thawr-4', 'jabal-thawr', 'ziyarats/jabal-thawr/thawr-4.jpg', 'image/jpeg', 853942, 1254, 1254, 3, '2026-09-11T16:30:00.000Z'),
  ('thawr-5', 'jabal-thawr', 'ziyarats/jabal-thawr/thawr-5.jpg', 'image/jpeg', 711603, 1254, 1254, 4, '2026-09-11T16:30:00.000Z');

INSERT OR REPLACE INTO ziyarat_place_translations (place_id,locale,title,short_description,long_description,interesting_facts_json,visit_notes,created_at,updated_at) VALUES
  ('jabal-thawr', 'ru', 'Гора Савр / пещера Савр', 'Историческая гора к югу от Мекки с пещерой, связанной с хиджрой Пророка ﷺ в Медину.', 'Джабаль Савр — гора к югу от Мекки. Недалеко от её вершины находится пещера Савр, где Пророк Мухаммад ﷺ и Абу Бакр رضي الله عنه укрывались три ночи во время хиджры, прежде чем продолжить путь в Медину. В суре «Ат-Тауба», 9:40, упоминается событие двух спутников в пещере. Точка на карте указывает именно на пещеру; подъём к ней сложный и не должен восприниматься как обычная короткая прогулка.', '["Пещера Савр связана с хиджрой из Мекки в Медину.","Пророк ﷺ и Абу Бакр رضي الله عنه провели в пещере три ночи.","Событие двух спутников в пещере упоминается в суре «Ат-Тауба», 9:40."]', 'Историческая остановка. Метка показывает саму пещеру, однако подъём крутой и физически сложный. Следуйте указаниям живого гида и действующим местным правилам; для осмотра горы необязательно подниматься к пещере.', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z'),
  ('jabal-thawr', 'uz', 'Savr tog‘i / Savr g‘ori', 'Makka janubidagi tarixiy tog‘ va Payg‘ambarimiz ﷺning Madinaga hijrati bilan bog‘liq g‘or.', 'Jabal Savr — Makka janubidagi tog‘. Uning cho‘qqisiga yaqin joyda Savr g‘ori bor. Hijrat vaqtida Payg‘ambarimiz Muhammad ﷺ va Abu Bakr رضي الله عنه Madina tomon yo‘lni davom ettirishdan oldin bu g‘orda uch kecha panoh topganlar. Tavba surasining 9:40-oyatida g‘ordagi ikki hamroh voqeasi eslatiladi. Xarita belgisi aynan g‘orni ko‘rsatadi; unga chiqish tik va jismonan og‘ir bo‘lib, oddiy qisqa sayr sifatida qaralmasligi kerak.', '["Savr g‘ori Makkadan Madinaga hijrat bilan bog‘liq.","Payg‘ambarimiz ﷺ va Abu Bakr رضي الله عنه g‘orda uch kecha qolganlar.","G‘ordagi ikki hamroh voqeasi Tavba surasi 9:40-oyatida eslatiladi."]', 'Tarixiy to‘xtash. Xarita g‘orning o‘zini ko‘rsatadi, ammo ko‘tarilish tik va jismonan qiyin. Jonli gid va amaldagi mahalliy ko‘rsatmalarga rioya qiling; tog‘ni ko‘rish uchun g‘orgacha chiqish shart emas.', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z'),
  ('jabal-thawr', 'uz-cyrl', 'Савр тоғи / Савр ғори', 'Макка жанубидаги тарихий тоғ ва Пайғамбаримиз ﷺнинг Мадинага ҳижрати билан боғлиқ ғор.', 'Жабал Савр — Макка жанубидаги тоғ. Унинг чўққисига яқин жойда Савр ғори бор. Ҳижрат вақтида Пайғамбаримиз Муҳаммад ﷺ ва Абу Бакр رضي الله عنه Мадина томон йўлни давом эттиришдан олдин бу ғорда уч кеча паноҳ топганлар. Тавба сурасининг 9:40-оятида ғордаги икки ҳамроҳ воқеаси эслатилади. Харита белгиси айнан ғорни кўрсатади; унга чиқиш тик ва жисмонан оғир бўлиб, оддий қисқа сайр сифатида қаралмаслиги керак.', '["Савр ғори Маккадан Мадинага ҳижрат билан боғлиқ.","Пайғамбаримиз ﷺ ва Абу Бакр رضي الله عنه ғорда уч кеча қолганлар.","Ғордаги икки ҳамроҳ воқеаси Тавба сураси 9:40-оятида эслатилади."]', 'Тарихий тўхташ. Харита ғорнинг ўзини кўрсатади, аммо кўтарилиш тик ва жисмонан қийин. Жонли гид ва амалдаги маҳаллий кўрсатмаларга риоя қилинг; тоғни кўриш учун ғоргача чиқиш шарт эмас.', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z'),
  ('jabal-thawr', 'en', 'Jabal Thawr / Cave of Thawr', 'A historic mountain south of Makkah, home to the cave associated with the Prophet’s ﷺ Hijrah to Madinah.', 'Jabal Thawr is a mountain south of Makkah. Near its summit is the Cave of Thawr, where the Prophet Muhammad ﷺ and Abu Bakr رضي الله عنه took refuge for three nights during the Hijrah before continuing toward Madinah. The Qur’an refers to the event of the two companions in the cave in Surah At-Tawbah 9:40. The saved map point marks the cave itself; reaching it requires a demanding mountain climb and should not be treated as an ordinary short walk.', '["The Cave of Thawr is connected with the Hijrah from Makkah to Madinah.","The Prophet ﷺ and Abu Bakr رضي الله عنه remained in the cave for three nights.","The Qur’an mentions the event of the two companions in the cave in Surah At-Tawbah 9:40."]', 'Historic stop. The map pin marks the cave, but the ascent is steep and physically demanding. Follow the live guide and current local access guidance; viewing the mountain does not require climbing to the cave.', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z');

INSERT OR REPLACE INTO ziyarat_places (
  id,route_id,slug,title,title_ar,category,short_description,long_description,interesting_facts_json,visit_notes,visit_type,duration_minutes,latitude,longitude,address,map_label,route_order,status,created_by,created_at,updated_at
) VALUES (
  'arafat-jabal-rahmah', 'makkah-main', 'arafat-jabal-rahmah', 'Arafat — Jabal al-Rahmah', 'عرفات — جبل الرحمة', 'mountain', 'The best-known hill on the Plain of Arafat, one of the central sacred areas of Hajj.', 'Jabal al-Rahmah, or the Mount of Mercy, is the best-known hill on the Plain of Arafat east of Makkah. Arafat is the central location of the Hajj standing on the ninth of Dhu al-Hijjah. The hill is a landmark within Arafat, but standing on or climbing the hill is not a requirement of Hajj; the standing takes place throughout the defined area of Arafat.', '["Jabal al-Rahmah is one of the most recognizable landmarks of Arafat.","The standing at Arafat on 9 Dhu al-Hijjah is a central rite of Hajj.","Climbing Jabal al-Rahmah is not required for the standing at Arafat."]', 'Sacred-site stop. Respect current crowd-control and access instructions. During Hajj, movement is highly regulated; outside Hajj the live guide should determine the practical stopping point.', 'stop', 30, 21.3548311, 39.9838861, 'Jabal al-Rahmah, Arafat, Makkah, Saudi Arabia', 'Jabal al-Rahmah · exact point', 2, 'published', 'seed', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z'
);

INSERT OR REPLACE INTO ziyarat_images (id,place_id,object_key,content_type,byte_size,width,height,position,created_at) VALUES
  ('arafat-1', 'arafat-jabal-rahmah', 'ziyarats/arafat-jabal-rahmah/arafat-1.jpg', 'image/jpeg', 660555, 1254, 1254, 0, '2026-09-11T16:30:00.000Z'),
  ('arafat-2', 'arafat-jabal-rahmah', 'ziyarats/arafat-jabal-rahmah/arafat-2.jpg', 'image/jpeg', 908449, 1254, 1254, 1, '2026-09-11T16:30:00.000Z'),
  ('arafat-3', 'arafat-jabal-rahmah', 'ziyarats/arafat-jabal-rahmah/arafat-3.jpg', 'image/jpeg', 523253, 1254, 1254, 2, '2026-09-11T16:30:00.000Z'),
  ('arafat-4', 'arafat-jabal-rahmah', 'ziyarats/arafat-jabal-rahmah/arafat-4.jpg', 'image/jpeg', 485560, 1254, 1254, 3, '2026-09-11T16:30:00.000Z'),
  ('arafat-5', 'arafat-jabal-rahmah', 'ziyarats/arafat-jabal-rahmah/arafat-5.jpg', 'image/jpeg', 690125, 1254, 1254, 4, '2026-09-11T16:30:00.000Z');

INSERT OR REPLACE INTO ziyarat_place_translations (place_id,locale,title,short_description,long_description,interesting_facts_json,visit_notes,created_at,updated_at) VALUES
  ('arafat-jabal-rahmah', 'ru', 'Арафат — Джабаль ар-Рахма', 'Самая известная возвышенность на равнине Арафат — одной из центральных священных территорий хаджа.', 'Джабаль ар-Рахма, или Гора Милости, — самая известная возвышенность на равнине Арафат к востоку от Мекки. Арафат является местом главного стояния хаджа 9 Зуль-хиджа. Сама гора служит ориентиром внутри Арафата, однако стоять именно на ней или подниматься на неё для хаджа не требуется: стояние действительно на всей установленной территории Арафата.', '["Джабаль ар-Рахма — один из самых узнаваемых ориентиров Арафата.","Стояние на Арафате 9 Зуль-хиджа — центральный обряд хаджа.","Подъём на Джабаль ар-Рахма не является условием стояния на Арафате."]', 'Остановка на священной территории. Соблюдайте действующие правила доступа и управления потоками людей. Во время хаджа движение строго регулируется; вне хаджа практическую точку остановки определяет живой гид.', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z'),
  ('arafat-jabal-rahmah', 'uz', 'Arafot — Jabal ar-Rahma', 'Arafot vodiysidagi eng mashhur tepalik va Hajning markaziy muqaddas hududlaridan biri.', 'Jabal ar-Rahma, ya’ni Rahmat tog‘i, Makka sharqidagi Arafot vodiysining eng mashhur tepaligidir. Arafot 9 Zulhijja kuni Hajdagi asosiy wuquf joyidir. Tog‘ Arafot ichidagi mashhur belgi, ammo Haj uchun aynan tog‘ ustida turish yoki unga chiqish shart emas; wuquf Arafotning belgilangan hududi bo‘ylab amalga oshadi.', '["Jabal ar-Rahma Arafotning eng taniqli belgilaridan biridir.","9 Zulhijja kuni Arafotda turish Hajning markaziy ruknlaridan biridir.","Jabal ar-Rahmaga chiqish Arafotdagi wuquf uchun shart emas."]', 'Muqaddas hududdagi to‘xtash. Amaldagi kirish va odamlar oqimini boshqarish ko‘rsatmalariga rioya qiling. Haj vaqtida harakat qat’iy tartibga solinadi; boshqa paytda amaliy to‘xtash nuqtasini jonli gid belgilaydi.', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z'),
  ('arafat-jabal-rahmah', 'uz-cyrl', 'Арафот — Жабал ар-Раҳма', 'Арафот водийсидаги энг машҳур тепалик ва Ҳажнинг марказий муқаддас ҳудудларидан бири.', 'Жабал ар-Раҳма, яъни Раҳмат тоғи, Макка шарқидаги Арафот водийсининг энг машҳур тепалигидир. Арафот 9 Зулҳижжа куни Ҳаждаги асосий вуқуф жойидир. Тоғ Арафот ичидаги машҳур белги, аммо Ҳаж учун айнан тоғ устида туриш ёки унга чиқиш шарт эмас; вуқуф Арафотнинг белгиланган ҳудуди бўйлаб амалга ошади.', '["Жабал ар-Раҳма Арафотнинг энг таниқли белгиларидан биридир.","9 Зулҳижжа куни Арафотда туриш Ҳажнинг марказий рукнларидан биридир.","Жабал ар-Раҳмага чиқиш Арафотдаги вуқуф учун шарт эмас."]', 'Муқаддас ҳудуддаги тўхташ. Амалдаги кириш ва одамлар оқимини бошқариш кўрсатмаларига риоя қилинг. Ҳаж вақтида ҳаракат қатъий тартибга солинади; бошқа пайтда амалий тўхташ нуқтасини жонли гид белгилайди.', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z'),
  ('arafat-jabal-rahmah', 'en', 'Arafat — Jabal al-Rahmah', 'The best-known hill on the Plain of Arafat, one of the central sacred areas of Hajj.', 'Jabal al-Rahmah, or the Mount of Mercy, is the best-known hill on the Plain of Arafat east of Makkah. Arafat is the central location of the Hajj standing on the ninth of Dhu al-Hijjah. The hill is a landmark within Arafat, but standing on or climbing the hill is not a requirement of Hajj; the standing takes place throughout the defined area of Arafat.', '["Jabal al-Rahmah is one of the most recognizable landmarks of Arafat.","The standing at Arafat on 9 Dhu al-Hijjah is a central rite of Hajj.","Climbing Jabal al-Rahmah is not required for the standing at Arafat."]', 'Sacred-site stop. Respect current crowd-control and access instructions. During Hajj, movement is highly regulated; outside Hajj the live guide should determine the practical stopping point.', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z');

INSERT OR REPLACE INTO ziyarat_places (
  id,route_id,slug,title,title_ar,category,short_description,long_description,interesting_facts_json,visit_notes,visit_type,duration_minutes,latitude,longitude,address,map_label,route_order,status,created_by,created_at,updated_at
) VALUES (
  'muzdalifah', 'makkah-main', 'muzdalifah-al-mashar-al-haram', 'Muzdalifah — Al-Mash’ar al-Haram', 'مزدلفة — المشعر الحرام', 'historical', 'The sacred Hajj site between Arafat and Mina, anchored on the map by Al-Mash’ar al-Haram Mosque.', 'Muzdalifah is the sacred area between Arafat and Mina. During Hajj, pilgrims arrive here after leaving Arafat, combine the Maghrib and Isha prayers, spend the night and then continue toward Mina. Al-Mash’ar al-Haram Mosque is a clear landmark within Muzdalifah and provides a precise map point for this route.', '["Muzdalifah lies between Arafat and Mina.","Pilgrims come here after the standing at Arafat and continue to Mina afterward.","Al-Mash’ar al-Haram Mosque is one of the principal landmarks within Muzdalifah."]', 'Sacred-site stop. Hajj-season access and traffic patterns are tightly controlled. The exact pin is the Al-Mash’ar al-Haram Mosque; follow the live guide and official directions for the usable meeting or stopping area.', 'stop', 25, 21.3862222, 39.9124722, 'Al-Mash’ar al-Haram Mosque, Muzdalifah, Makkah, Saudi Arabia', 'Al-Mash’ar al-Haram · Muzdalifah', 3, 'published', 'seed', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z'
);

INSERT OR REPLACE INTO ziyarat_images (id,place_id,object_key,content_type,byte_size,width,height,position,created_at) VALUES
  ('muzdalifah-1', 'muzdalifah', 'ziyarats/muzdalifah/muzdalifah-1.jpg', 'image/jpeg', 524813, 1254, 1254, 0, '2026-09-11T16:30:00.000Z'),
  ('muzdalifah-2', 'muzdalifah', 'ziyarats/muzdalifah/muzdalifah-2.jpg', 'image/jpeg', 561986, 1254, 1254, 1, '2026-09-11T16:30:00.000Z'),
  ('muzdalifah-3', 'muzdalifah', 'ziyarats/muzdalifah/muzdalifah-3.jpg', 'image/jpeg', 713572, 1254, 1254, 2, '2026-09-11T16:30:00.000Z'),
  ('muzdalifah-4', 'muzdalifah', 'ziyarats/muzdalifah/muzdalifah-4.jpg', 'image/jpeg', 459896, 1254, 1254, 3, '2026-09-11T16:30:00.000Z'),
  ('muzdalifah-5', 'muzdalifah', 'ziyarats/muzdalifah/muzdalifah-5.jpg', 'image/jpeg', 538114, 1254, 1254, 4, '2026-09-11T16:30:00.000Z');

INSERT OR REPLACE INTO ziyarat_place_translations (place_id,locale,title,short_description,long_description,interesting_facts_json,visit_notes,created_at,updated_at) VALUES
  ('muzdalifah', 'ru', 'Муздалифа — Аль-Маш‘ар аль-Харам', 'Священная территория хаджа между Арафатом и Миной; точка на карте привязана к мечети Аль-Маш‘ар аль-Харам.', 'Муздалифа — священная территория между Арафатом и Миной. Во время хаджа паломники прибывают сюда после Арафата, совмещают намазы Магриб и Иша, проводят здесь ночь и затем направляются в Мину. Мечеть Аль-Маш‘ар аль-Харам является понятным ориентиром внутри Муздалифы и используется как точная точка этого маршрута на карте.', '["Муздалифа находится между Арафатом и Миной.","Паломники прибывают сюда после стояния на Арафате и затем направляются в Мину.","Мечеть Аль-Маш‘ар аль-Харам — один из главных ориентиров Муздалифы."]', 'Остановка на священной территории. В сезон хаджа доступ и движение транспорта строго регулируются. Точная метка — мечеть Аль-Маш‘ар аль-Харам; следуйте указаниям живого гида и официальным схемам движения.', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z'),
  ('muzdalifah', 'uz', 'Muzdalifa — Al-Mash’ar al-Haram', 'Arafot bilan Mina orasidagi muqaddas Haj hududi; xarita nuqtasi Al-Mash’ar al-Haram masjidiga bog‘langan.', 'Muzdalifa — Arafot va Mina orasidagi muqaddas hudud. Hajda ziyoratchilar Arafotdan keyin bu yerga keladilar, Shom va Xufton namozlarini jam qiladilar, tunab qoladilar va keyin Mina tomon yo‘l oladilar. Al-Mash’ar al-Haram masjidi Muzdalifadagi aniq va tanish orientir bo‘lib, iumrah xaritasida shu nuqta saqlanadi.', '["Muzdalifa Arafot bilan Mina orasida joylashgan.","Ziyoratchilar Arafotdagi wuqufdan keyin bu yerga kelib, so‘ng Mina tomon yo‘l oladilar.","Al-Mash’ar al-Haram masjidi Muzdalifadagi asosiy orientirlardan biridir."]', 'Muqaddas hududdagi to‘xtash. Haj mavsumida kirish va transport harakati qat’iy boshqariladi. Aniq belgi Al-Mash’ar al-Haram masjididir; jonli gid va rasmiy harakat ko‘rsatmalariga rioya qiling.', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z'),
  ('muzdalifah', 'uz-cyrl', 'Муздалифа — Ал-Машъар ал-Ҳарам', 'Арафот билан Мина орасидаги муқаддас Ҳаж ҳудуди; харита нуқтаси Ал-Машъар ал-Ҳарам масжидига боғланган.', 'Муздалифа — Арафот ва Мина орасидаги муқаддас ҳудуд. Ҳажда зиёратчилар Арафотдан кейин бу ерга келадилар, Шом ва Хуфтон намозларини жам қиладилар, тунаб қоладилар ва кейин Мина томон йўл оладилар. Ал-Машъар ал-Ҳарам масжиди Муздалифадаги аниқ ва таниш ориентир бўлиб, iumrah харитасида шу нуқта сақланади.', '["Муздалифа Арафот билан Мина орасида жойлашган.","Зиёратчилар Арафотдаги вуқуфдан кейин бу ерга келиб, сўнг Мина томон йўл оладилар.","Ал-Машъар ал-Ҳарам масжиди Муздалифадаги асосий ориентирлардан биридир."]', 'Муқаддас ҳудуддаги тўхташ. Ҳаж мавсумида кириш ва транспорт ҳаракати қатъий бошқарилади. Аниқ белги Ал-Машъар ал-Ҳарам масжидидир; жонли гид ва расмий ҳаракат кўрсатмаларига риоя қилинг.', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z'),
  ('muzdalifah', 'en', 'Muzdalifah — Al-Mash’ar al-Haram', 'The sacred Hajj site between Arafat and Mina, anchored on the map by Al-Mash’ar al-Haram Mosque.', 'Muzdalifah is the sacred area between Arafat and Mina. During Hajj, pilgrims arrive here after leaving Arafat, combine the Maghrib and Isha prayers, spend the night and then continue toward Mina. Al-Mash’ar al-Haram Mosque is a clear landmark within Muzdalifah and provides a precise map point for this route.', '["Muzdalifah lies between Arafat and Mina.","Pilgrims come here after the standing at Arafat and continue to Mina afterward.","Al-Mash’ar al-Haram Mosque is one of the principal landmarks within Muzdalifah."]', 'Sacred-site stop. Hajj-season access and traffic patterns are tightly controlled. The exact pin is the Al-Mash’ar al-Haram Mosque; follow the live guide and official directions for the usable meeting or stopping area.', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z');

INSERT OR REPLACE INTO ziyarat_places (
  id,route_id,slug,title,title_ar,category,short_description,long_description,interesting_facts_json,visit_notes,visit_type,duration_minutes,latitude,longitude,address,map_label,route_order,status,created_by,created_at,updated_at
) VALUES (
  'mina-holy-site', 'makkah-main', 'mina-holy-site', 'Mina Holy Site', 'مشعر منى', 'historical', 'The major Hajj valley closest to the Grand Mosque, famous for its vast seasonal tent city.', 'Mina is a sacred Hajj site in a valley east of the Grand Mosque. Pilgrims stay here on the Day of Tarwiyah and return during the Days of Tashriq. The area contains the Jamarat Complex and Al-Khayf Mosque and becomes one of the largest temporary accommodation areas in the world during Hajj, with extensive fire-resistant tent infrastructure.', '["Mina is the closest of the main Hajj holy sites to Al-Masjid al-Haram.","It is widely known for its enormous seasonal tent city.","The Jamarat Complex and Al-Khayf Mosque are located within Mina."]', 'Area stop. Mina is very large; this marker is a central route reference, while the live guide should use the group’s current camp, road and access plan. Hajj-season entry and traffic controls can change.', 'stop', 30, 21.4133333, 39.8933333, 'Mina Holy Site, Makkah, Saudi Arabia', 'Mina Holy Site · central point', 4, 'published', 'seed', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z'
);

INSERT OR REPLACE INTO ziyarat_images (id,place_id,object_key,content_type,byte_size,width,height,position,created_at) VALUES
  ('mina-1', 'mina-holy-site', 'ziyarats/mina-holy-site/mina-1.jpg', 'image/jpeg', 972484, 1254, 1254, 0, '2026-09-11T16:30:00.000Z'),
  ('mina-2', 'mina-holy-site', 'ziyarats/mina-holy-site/mina-2.jpg', 'image/jpeg', 702671, 1254, 1254, 1, '2026-09-11T16:30:00.000Z'),
  ('mina-3', 'mina-holy-site', 'ziyarats/mina-holy-site/mina-3.jpg', 'image/jpeg', 552947, 1254, 1254, 2, '2026-09-11T16:30:00.000Z'),
  ('mina-4', 'mina-holy-site', 'ziyarats/mina-holy-site/mina-4.jpg', 'image/jpeg', 515246, 1254, 1254, 3, '2026-09-11T16:30:00.000Z'),
  ('mina-5', 'mina-holy-site', 'ziyarats/mina-holy-site/mina-5.jpg', 'image/jpeg', 600900, 1254, 1254, 4, '2026-09-11T16:30:00.000Z');

INSERT OR REPLACE INTO ziyarat_place_translations (place_id,locale,title,short_description,long_description,interesting_facts_json,visit_notes,created_at,updated_at) VALUES
  ('mina-holy-site', 'ru', 'Мина', 'Крупная долина хаджа, ближайшая к Заповедной мечети и известная огромным сезонным городом палаток.', 'Мина — священная территория хаджа в долине к востоку от Аль-Масджид аль-Харам. Паломники находятся здесь в День Тарвия и возвращаются в дни Ташрика. На территории расположены комплекс Джамарат и мечеть Аль-Хайф, а во время хаджа Мина превращается в один из крупнейших временных городов размещения с масштабной системой огнестойких палаток.', '["Мина — ближайшая к Аль-Масджид аль-Харам из основных священных территорий хаджа.","Она известна огромным сезонным палаточным городом.","В Мине находятся комплекс Джамарат и мечеть Аль-Хайф."]', 'Остановка по территории. Мина очень большая; эта метка служит центральным ориентиром маршрута, а живой гид должен учитывать текущий лагерь группы, дорогу и схему доступа. В сезон хаджа правила движения могут меняться.', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z'),
  ('mina-holy-site', 'uz', 'Mina', 'Masjid al-Haramga eng yaqin asosiy Haj vodiysi va ulkan mavsumiy chodir shaharchasi bilan mashhur hudud.', 'Mina — Masjid al-Haramning sharqidagi vodiyda joylashgan muqaddas Haj hududi. Ziyoratchilar Tarviya kuni bu yerda bo‘ladilar va Tashriq kunlarida yana qaytadilar. Hududda Jamarot majmuasi va Al-Xayf masjidi joylashgan. Haj mavsumida Mina yong‘inga chidamli ulkan chodir infratuzilmasi bilan dunyodagi eng katta vaqtinchalik yashash hududlaridan biriga aylanadi.', '["Mina asosiy Haj hududlari ichida Masjid al-Haramga eng yaqinidir.","U ulkan mavsumiy chodir shaharchasi bilan mashhur.","Jamarot majmuasi va Al-Xayf masjidi Mina hududida joylashgan."]', 'Hudud bo‘ylab to‘xtash. Mina juda katta; bu belgi yo‘nalishning markaziy orientiri, amaliy uchrashuv nuqtasini esa jonli gid guruh lageri, yo‘l va kirish tartibiga qarab belgilaydi. Haj mavsumida harakat qoidalari o‘zgarishi mumkin.', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z'),
  ('mina-holy-site', 'uz-cyrl', 'Мина', 'Масжид ал-Ҳарамга энг яқин асосий Ҳаж водийси ва улкан мавсумий чодир шаҳарчаси билан машҳур ҳудуд.', 'Мина — Масжид ал-Ҳарамнинг шарқидаги водийда жойлашган муқаддас Ҳаж ҳудуди. Зиёратчилар Тарвия куни бу ерда бўладилар ва Ташриқ кунларида яна қайтадилар. Ҳудудда Жамарот мажмуаси ва Ал-Хайф масжиди жойлашган. Ҳаж мавсумида Мина ёнғинга чидамли улкан чодир инфратузилмаси билан дунёдаги энг катта вақтинчалик яшаш ҳудудларидан бирига айланади.', '["Мина асосий Ҳаж ҳудудлари ичида Масжид ал-Ҳарамга энг яқинидир.","У улкан мавсумий чодир шаҳарчаси билан машҳур.","Жамарот мажмуаси ва Ал-Хайф масжиди Мина ҳудудида жойлашган."]', 'Ҳудуд бўйлаб тўхташ. Мина жуда катта; бу белги йўналишнинг марказий ориентири, амалий учрашув нуқтасини эса жонли гид гуруҳ лагери, йўл ва кириш тартибига қараб белгилайди. Ҳаж мавсумида ҳаракат қоидалари ўзгариши мумкин.', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z'),
  ('mina-holy-site', 'en', 'Mina', 'The major Hajj valley closest to the Grand Mosque, famous for its vast seasonal tent city.', 'Mina is a sacred Hajj site in a valley east of the Grand Mosque. Pilgrims stay here on the Day of Tarwiyah and return during the Days of Tashriq. The area contains the Jamarat Complex and Al-Khayf Mosque and becomes one of the largest temporary accommodation areas in the world during Hajj, with extensive fire-resistant tent infrastructure.', '["Mina is the closest of the main Hajj holy sites to Al-Masjid al-Haram.","It is widely known for its enormous seasonal tent city.","The Jamarat Complex and Al-Khayf Mosque are located within Mina."]', 'Area stop. Mina is very large; this marker is a central route reference, while the live guide should use the group’s current camp, road and access plan. Hajj-season entry and traffic controls can change.', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z');

INSERT OR REPLACE INTO ziyarat_places (
  id,route_id,slug,title,title_ar,category,short_description,long_description,interesting_facts_json,visit_notes,visit_type,duration_minutes,latitude,longitude,address,map_label,route_order,status,created_by,created_at,updated_at
) VALUES (
  'jamarat-complex', 'makkah-main', 'jamarat-complex', 'Jamarat Complex', 'منشأة الجمرات / جسر الجمرات', 'landmark', 'The multi-level complex in Mina where the three Jamarat are located and the Hajj rite of ramy is performed.', 'The Jamarat Complex in Mina is designed for the Hajj rite of casting pebbles at the three Jamarat: al-Sughra, al-Wusta and al-Kubra, also called al-Aqabah. The modern complex has five levels, multiple entrances and exits, tunnels and cooling systems to manage very large pedestrian flows. The exact map point is placed on the Jamarat Bridge complex rather than on a generic Mina coordinate.', '["The complex contains the three Jamarat: al-Sughra, al-Wusta and al-Kubra/al-Aqabah.","The current Jamarat Complex has five levels.","Its circulation systems are designed to handle very large Hajj pedestrian flows."]', 'Hajj-ritual site. Do not use this card as a substitute for ritual instruction or official crowd-control directions. During Hajj, follow the guide, Nusuk/official scheduling and the designated access route.', 'stop', 30, 21.4213889, 39.8728056, 'Jamarat Complex, Mina, Makkah, Saudi Arabia', 'Jamarat Complex · exact point', 5, 'published', 'seed', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z'
);

INSERT OR REPLACE INTO ziyarat_images (id,place_id,object_key,content_type,byte_size,width,height,position,created_at) VALUES
  ('jamarat-1', 'jamarat-complex', 'ziyarats/jamarat-complex/jamarat-1.jpg', 'image/jpeg', 924501, 1254, 1254, 0, '2026-09-11T16:30:00.000Z'),
  ('jamarat-2', 'jamarat-complex', 'ziyarats/jamarat-complex/jamarat-2.jpg', 'image/jpeg', 839785, 1254, 1254, 1, '2026-09-11T16:30:00.000Z'),
  ('jamarat-3', 'jamarat-complex', 'ziyarats/jamarat-complex/jamarat-3.jpg', 'image/jpeg', 563794, 1254, 1254, 2, '2026-09-11T16:30:00.000Z'),
  ('jamarat-4', 'jamarat-complex', 'ziyarats/jamarat-complex/jamarat-4.jpg', 'image/jpeg', 559966, 1254, 1254, 3, '2026-09-11T16:30:00.000Z'),
  ('jamarat-5', 'jamarat-complex', 'ziyarats/jamarat-complex/jamarat-5.jpg', 'image/jpeg', 493905, 1254, 1254, 4, '2026-09-11T16:30:00.000Z');

INSERT OR REPLACE INTO ziyarat_place_translations (place_id,locale,title,short_description,long_description,interesting_facts_json,visit_notes,created_at,updated_at) VALUES
  ('jamarat-complex', 'ru', 'Комплекс Джамарат', 'Многоуровневый комплекс в Мине, где находятся три Джамарата и совершается обряд рамй во время хаджа.', 'Комплекс Джамарат в Мине предназначен для обряда бросания камешков в три Джамарата: ас-Сугра, аль-Вуста и аль-Кубра, также называемый аль-Акаба. Современный комплекс имеет пять уровней, многочисленные входы и выходы, тоннели и системы охлаждения для управления огромными потоками паломников. Точная метка на карте поставлена на комплекс моста Джамарат, а не на условную точку Мины.', '["Комплекс включает три Джамарата: ас-Сугра, аль-Вуста и аль-Кубра/аль-Акаба.","Современный комплекс Джамарат имеет пять уровней.","Система движения комплекса рассчитана на очень большие потоки паломников во время хаджа."]', 'Место обряда хаджа. Эта карточка не заменяет руководство по манасикам и официальные указания по движению толпы. Во время хаджа следуйте живому гиду, официальному расписанию/Nusuk и назначенному маршруту доступа.', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z'),
  ('jamarat-complex', 'uz', 'Jamarot majmuasi', 'Minadagi uchta Jamarot joylashgan va Hajda ramy amali bajariladigan ko‘p qavatli majmua.', 'Minadagi Jamarot majmuasi Haj vaqtida uchta Jamarot — as-Sug‘ro, al-Vusto va al-Kubro (al-Aqaba)ga tosh otish amali uchun tashkil etilgan. Zamonaviy majmua besh qavat, ko‘plab kirish-chiqishlar, tunnellar va juda katta piyoda oqimini boshqarishga mo‘ljallangan sovitish tizimlariga ega. Xarita belgisi Minaning umumiy nuqtasiga emas, aynan Jamarot ko‘prigi majmuasiga qo‘yilgan.', '["Majmuada uchta Jamarot bor: as-Sug‘ro, al-Vusto va al-Kubro/al-Aqaba.","Hozirgi Jamarot majmuasi besh qavatdan iborat.","Harakat tizimlari Hajdagi juda katta piyoda oqimini boshqarish uchun loyihalangan."]', 'Haj marosimi joyi. Bu karta manasik bo‘yicha yo‘riqnoma yoki rasmiy odamlar oqimini boshqarish ko‘rsatmalarining o‘rnini bosmaydi. Hajda jonli gid, rasmiy/Nusuk jadvali va belgilangan kirish yo‘liga rioya qiling.', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z'),
  ('jamarat-complex', 'uz-cyrl', 'Жамарот мажмуаси', 'Минадаги учта Жамарот жойлашган ва Ҳажда рамй амали бажариладиган кўп қаватли мажмуа.', 'Минадаги Жамарот мажмуаси Ҳаж вақтида учта Жамарот — ас-Суғро, ал-Вусто ва ал-Кубро (ал-Ақаба)га тош отиш амали учун ташкил этилган. Замонавий мажмуа беш қават, кўплаб кириш-чиқишлар, туннеллар ва жуда катта пиёда оқимини бошқаришга мўлжалланган совитиш тизимларига эга. Харита белгиси Минанинг умумий нуқтасига эмас, айнан Жамарот кўприги мажмуасига қўйилган.', '["Мажмуада учта Жамарот бор: ас-Суғро, ал-Вусто ва ал-Кубро/ал-Ақаба.","Ҳозирги Жамарот мажмуаси беш қаватдан иборат.","Ҳаракат тизимлари Ҳаждаги жуда катта пиёда оқимини бошқариш учун лойиҳаланган."]', 'Ҳаж маросими жойи. Бу карта манасик бўйича йўриқнома ёки расмий одамлар оқимини бошқариш кўрсатмаларининг ўрнини босмайди. Ҳажда жонли гид, расмий/Nusuk жадвали ва белгиланган кириш йўлига риоя қилинг.', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z'),
  ('jamarat-complex', 'en', 'Jamarat Complex', 'The multi-level complex in Mina where the three Jamarat are located and the Hajj rite of ramy is performed.', 'The Jamarat Complex in Mina is designed for the Hajj rite of casting pebbles at the three Jamarat: al-Sughra, al-Wusta and al-Kubra, also called al-Aqabah. The modern complex has five levels, multiple entrances and exits, tunnels and cooling systems to manage very large pedestrian flows. The exact map point is placed on the Jamarat Bridge complex rather than on a generic Mina coordinate.', '["The complex contains the three Jamarat: al-Sughra, al-Wusta and al-Kubra/al-Aqabah.","The current Jamarat Complex has five levels.","Its circulation systems are designed to handle very large Hajj pedestrian flows."]', 'Hajj-ritual site. Do not use this card as a substitute for ritual instruction or official crowd-control directions. During Hajj, follow the guide, Nusuk/official scheduling and the designated access route.', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z');

INSERT OR REPLACE INTO ziyarat_places (
  id,route_id,slug,title,title_ar,category,short_description,long_description,interesting_facts_json,visit_notes,visit_type,duration_minutes,latitude,longitude,address,map_label,route_order,status,created_by,created_at,updated_at
) VALUES (
  'masjid-al-haram', 'makkah-main', 'masjid-al-haram', 'Al-Masjid al-Haram', 'المسجد الحرام', 'mosque', 'Islam’s holiest mosque in Makkah, surrounding the Kaaba and serving as the central destination of Hajj and Umrah.', 'Al-Masjid al-Haram is the Sacred Mosque of Makkah and surrounds the Kaaba, the qiblah toward which Muslims pray. It is the central destination of Hajj and Umrah and includes the Mataf for tawaf as well as access associated with Zamzam and the Mas‘a between Safa and Marwah. The map point is centered on the Kaaba so the user is taken to the heart of the mosque rather than a random gate or nearby hotel.', '["The Kaaba stands at the center of Al-Masjid al-Haram and is the qiblah for Muslim prayer.","Tawaf is performed around the Kaaba in the Mataf.","The mosque is the central sacred destination for both Hajj and Umrah."]', 'Main sacred stop. Visit time is flexible and may be much longer than the route estimate, especially for prayer, tawaf or Umrah. Entrances, crowd routes and access zones change with prayer times and seasons; follow official directions and the live guide.', 'enter', 90, 21.4225, 39.8261667, 'Al-Masjid al-Haram, Al Haram, Makkah, Saudi Arabia', 'Al-Masjid al-Haram · Kaaba center', 6, 'published', 'seed', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z'
);

INSERT OR REPLACE INTO ziyarat_images (id,place_id,object_key,content_type,byte_size,width,height,position,created_at) VALUES
  ('haram-1', 'masjid-al-haram', 'ziyarats/masjid-al-haram/haram-1.jpg', 'image/jpeg', 611107, 1254, 1254, 0, '2026-09-11T16:30:00.000Z'),
  ('haram-2', 'masjid-al-haram', 'ziyarats/masjid-al-haram/haram-2.jpg', 'image/jpeg', 671581, 1254, 1254, 1, '2026-09-11T16:30:00.000Z'),
  ('haram-3', 'masjid-al-haram', 'ziyarats/masjid-al-haram/haram-3.jpg', 'image/jpeg', 609626, 1254, 1254, 2, '2026-09-11T16:30:00.000Z'),
  ('haram-4', 'masjid-al-haram', 'ziyarats/masjid-al-haram/haram-4.jpg', 'image/jpeg', 483316, 1254, 1254, 3, '2026-09-11T16:30:00.000Z'),
  ('haram-5', 'masjid-al-haram', 'ziyarats/masjid-al-haram/haram-5.jpg', 'image/jpeg', 849099, 1254, 1254, 4, '2026-09-11T16:30:00.000Z'),
  ('haram-6', 'masjid-al-haram', 'ziyarats/masjid-al-haram/haram-6.jpg', 'image/jpeg', 587844, 1254, 1254, 5, '2026-09-11T16:30:00.000Z');

INSERT OR REPLACE INTO ziyarat_place_translations (place_id,locale,title,short_description,long_description,interesting_facts_json,visit_notes,created_at,updated_at) VALUES
  ('masjid-al-haram', 'ru', 'Аль-Масджид аль-Харам', 'Главная святыня ислама в Мекке, окружающая Каабу и являющаяся центральным местом хаджа и умры.', 'Аль-Масджид аль-Харам — Заповедная мечеть Мекки, окружающая Каабу, к которой мусульмане обращаются во время намаза. Это центральное место хаджа и умры. В комплекс входит Матaф для тавафа, а также зоны, связанные с Замзамом и Мас‘а между Сафа и Марва. Точка на карте поставлена на центр Каабы, чтобы пользователь попадал к сердцу мечети, а не к случайным воротам или соседнему отелю.', '["Кааба находится в центре Аль-Масджид аль-Харам и является киблой для мусульманского намаза.","Таваф совершается вокруг Каабы в Матaфе.","Мечеть является центральной святыней и для хаджа, и для умры."]', 'Главная священная остановка. Время посещения гибкое и может значительно превышать расчёт маршрута, особенно при намазе, тавафе или умре. Входы и потоки людей меняются в зависимости от времени намаза и сезона; следуйте официальным указаниям и живому гиду.', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z'),
  ('masjid-al-haram', 'uz', 'Masjid al-Haram', 'Makkadagi Islomning eng muqaddas masjidi, Ka’bani o‘rab turadi va Haj hamda Umraning markaziy manzilidir.', 'Masjid al-Haram — Makkadagi Muqaddas masjid bo‘lib, musulmonlar namozda yuzlanadigan qibla — Ka’bani o‘rab turadi. U Haj va Umraning markaziy manzilidir. Majmuada Ka’ba atrofidagi Mataf, Zamzam bilan bog‘liq hududlar va Safo-Marva orasidagi Mas’a mavjud. Xarita nuqtasi tasodifiy darvoza yoki yaqin mehmonxonaga emas, aynan Ka’baning markaziga qo‘yilgan.', '["Ka’ba Masjid al-Haram markazida joylashgan va musulmonlar namozining qiblasidir.","Tavof Ka’ba atrofidagi Matafda bajariladi.","Masjid Haj va Umraning markaziy muqaddas manzilidir."]', 'Asosiy muqaddas to‘xtash. Tashrif vaqti erkin bo‘lib, namoz, tavof yoki Umra sabab yo‘nalish hisobidan ancha uzoq davom etishi mumkin. Kirishlar va odamlar oqimi namoz va mavsumga qarab o‘zgaradi; rasmiy ko‘rsatmalar va jonli gidga rioya qiling.', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z'),
  ('masjid-al-haram', 'uz-cyrl', 'Масжид ал-Ҳарам', 'Маккадаги Исломнинг энг муқаддас масжиди, Каъбани ўраб туради ва Ҳаж ҳамда Умранинг марказий манзилидир.', 'Масжид ал-Ҳарам — Маккадаги Муқаддас масжид бўлиб, мусулмонлар намозда юзланадиган қибла — Каъбани ўраб туради. У Ҳаж ва Умранинг марказий манзилидир. Мажмуада Каъба атрофидаги Матаф, Замзам билан боғлиқ ҳудудлар ва Сафо-Марва орасидаги Масъа мавжуд. Харита нуқтаси тасодифий дарвоза ёки яқин меҳмонхонага эмас, айнан Каъбанинг марказига қўйилган.', '["Каъба Масжид ал-Ҳарам марказида жойлашган ва мусулмонлар намозининг қибласидир.","Тавоф Каъба атрофидаги Матафда бажарилади.","Масжид Ҳаж ва Умранинг марказий муқаддас манзилидир."]', 'Асосий муқаддас тўхташ. Ташриф вақти эркин бўлиб, намоз, тавоф ёки Умра сабаб йўналиш ҳисобидан анча узоқ давом этиши мумкин. Киришлар ва одамлар оқими намоз ва мавсумга қараб ўзгаради; расмий кўрсатмалар ва жонли гидга риоя қилинг.', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z'),
  ('masjid-al-haram', 'en', 'Al-Masjid al-Haram', 'Islam’s holiest mosque in Makkah, surrounding the Kaaba and serving as the central destination of Hajj and Umrah.', 'Al-Masjid al-Haram is the Sacred Mosque of Makkah and surrounds the Kaaba, the qiblah toward which Muslims pray. It is the central destination of Hajj and Umrah and includes the Mataf for tawaf as well as access associated with Zamzam and the Mas‘a between Safa and Marwah. The map point is centered on the Kaaba so the user is taken to the heart of the mosque rather than a random gate or nearby hotel.', '["The Kaaba stands at the center of Al-Masjid al-Haram and is the qiblah for Muslim prayer.","Tawaf is performed around the Kaaba in the Mataf.","The mosque is the central sacred destination for both Hajj and Umrah."]', 'Main sacred stop. Visit time is flexible and may be much longer than the route estimate, especially for prayer, tawaf or Umrah. Entrances, crowd routes and access zones change with prayer times and seasons; follow official directions and the live guide.', '2026-09-11T16:30:00.000Z', '2026-09-11T16:30:00.000Z');
